---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: test
resources:
  - ../common
  - hpa.yaml
patches:
  - target:
      version: v1
      kind: Deployment
      name: testdeploy
    patch: |-
      - op: replace
        path: /metadata/name
        value: pod1
