---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testdeploy
  namespace: test
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: testdeploy
          image: nginx
          env: []
